server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_manager
    username: root
    password: NewRootPass123!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: my-super-secret-key-my-super-secret-key
  expiration: 86400000

---


